version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: alibou
      POSTGRES_PASSWORD: alibou
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices_net
    restart: unless-stopped
  # pgAdmin Service
  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices_net
    restart: unless-stopped

  # MongoDB Service
  mongodb:
    container_name: ms_mongo_db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alibou
      - MONGO_INITDB_ROOT_PASSWORD=alibou
    volumes:
      - mongo:/data
    ports:
      - 27017:27017
    networks:
      - microservices_net
    restart: unless-stopped

  # Mongo Express Service
  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=alibou
      - ME_CONFIG_MONGODB_ADMINPASSWORD=alibou
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081
    networks:
      - microservices_net
    restart: unless-stopped

  # MailDev Service
  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - microservices_net
    restart: unless-stopped

networks:
  microservices_net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
